# -*- coding: utf-8 -*-
"""Intrusion detectionRMF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T98fuDAQ8EJNk0GUSH56SRPCq2zqIsBb
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
import plotly.express as px
import plotly.graph_objects as go
# %matplotlib inline
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 150)
sns.set_style('darkgrid')
plt.rcParams['font.size'] = 14
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['patch.edgecolor'] = '#313338'
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

from google.colab import drive
drive.mount('/content/drive', force_remount=True)
monday=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Monday-WorkingHours.pcap_ISCX.csv")
tuesday=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Tuesday-WorkingHours.pcap_ISCX.csv")
wednesday=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Wednesday-workingHours.pcap_ISCX.csv")
thursday_web=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv")
thursday_infilteration=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")
friday_morning=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Friday-WorkingHours-Morning.pcap_ISCX.csv")
friday_portscan=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv")
friday_DDos=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

monday["source"] = "Monday"
tuesday["source"] = "Tuesday"
wednesday["source"] = "Wednesday"
thursday_web["source"] = "Thursday-Web"
thursday_infilteration["source"] = "Thursday-Infiltration"
friday_morning["source"] = "Friday-Morning"
friday_portscan["source"] = "Friday-PortScan"
friday_DDos["source"] = "Friday-DDoS"

dfs = [monday, tuesday, wednesday, thursday_web,
       thursday_infilteration, friday_morning,
       friday_portscan, friday_DDos]
for df in dfs:
    df.columns = df.columns.str.strip()

for name, df in zip(
    ["Monday","Tuesday","Wednesday","Thursday-Web",
     "Thursday-Infiltration","Friday-Morning",
     "Friday-PortScan","Friday-DDoS"],
    dfs
):
    print("\n", name)
    print(df.describe())

for name, df in zip(
    ["Monday", "Tuesday", "Wednesday", "Thursday-Web",
     "Thursday-Infiltration", "Friday-Morning",
     "Friday-PortScan", "Friday-DDoS"],
    dfs
):
    print("\n", name)
    print(df["Label"].value_counts())

full_df = pd.concat(dfs, ignore_index=True)
full_df = full_df.replace([np.inf, -np.inf], np.nan).dropna()

sample = full_df.sample(5000)
sample['Binary'] = sample['Label'].apply(lambda x: "Attack" if x != "BENIGN" else "Benign")
fig = px.scatter(
    sample,
    x='Flow Duration',
    y='Total Length of Fwd Packets',
    color='Binary',
    title='Flow Duration vs Packet Size (Attack vs Benign)',
    opacity=0.6
)

fig.show()

fig = px.scatter(
    sample,
    x='Flow Packets/s',
    y='Flow Bytes/s',
    color='Binary',
    title='Packet Rate vs Byte Rate (Traffic Behavior)'
)

fig.show()

fig = px.histogram(
    sample,
    x='Flow Duration',
    color='Binary',
    title='Flow Duration Distribution (Attack vs Benign)',
    nbins=50
)

fig.show()

fig = px.histogram(
    sample,
    x='Total Length of Fwd Packets',
    color='Binary',
    title='Packet Size Distribution (Attack vs Benign)',
    nbins=50
)

fig.show()

fig = px.histogram(
    full_df,
    x='Label',
    color='Label',
    title='Distribution of Attack Categories'
)

fig.show()

fig = px.box(
    sample,
    x='Label',
    y='Flow Duration',
    color='Label',
    title='Flow Duration Spread per Attack Category'
)

fig.show()

fig = px.violin(
    sample,
    x='Binary',
    y='Flow Bytes/s',
    color='Binary',
    box=True,
    title='Traffic Intensity Distribution (Attack vs Benign)'
)

fig.show()

fig = px.scatter_matrix(
    sample,
    dimensions=['Flow Duration', 'Flow Bytes/s', 'Flow Packets/s'],
    color='Binary',
    title='Multi-Dimensional Traffic Behavior'
)

fig.show()

fig = px.histogram(
    full_df,
    x='source',
    color='Label',
    title='Attack Types Across Different Days'
)

fig.show()

fig = px.density_heatmap(
    sample,
    x='Flow Duration',
    y='Flow Bytes/s',
    color_continuous_scale='Viridis',
    title='Traffic Density Map'
)

fig.show()

fig = px.parallel_coordinates(
    sample,
    dimensions=['Flow Duration', 'Flow Bytes/s', 'Flow Packets/s'],
    color=sample['Binary'].map({'Benign':0, 'Attack':1}),
    title='Feature Interaction View (Parallel Coordinates)'
)

fig.show()

daily = full_df.groupby('source')['Label'].apply(lambda x: (x != 'BENIGN').sum())
fig = px.line(
    x=daily.index,
    y=daily.values,
    title='Attack Volume Trend Across Days',
    markers=True
)

fig.show()

trend = full_df.groupby('source')['Label'].value_counts().unstack()
fig = px.line(
    trend,
    x=trend.index,
    y=trend.columns,
    title='Benign vs Attack Trends Across Days',
    markers=True
)

fig.show()

attack_series = full_df['Label'].apply(lambda x: 1 if x != 'BENIGN' else 0).cumsum()
fig = px.line(
    x=range(len(attack_series)),
    y=attack_series,
    title='Cumulative Attack Detection Over Dataset'
)

fig.show()

roll = full_df['Flow Duration'].rolling(1000).mean()

fig = px.line(
    x=roll.index,
    y=roll.values,
    title='Rolling Mean of Flow Duration (Stability Pattern)'
)

fig.show()

fig = px.histogram(
    sample,
    x='Flow Bytes/s',
    color=sample['Label'].apply(lambda x: "Attack" if x != "BENIGN" else "Benign"),
    nbins=80,
    title='Flow Bytes/s Distribution Comparison'
)

fig.show()

fig = px.box(
    full_df,
    x='source',
    y='Flow Duration',
    title='Feature Drift: Flow Duration Across Days'
)

fig.show()

fig = px.density_heatmap(
    sample,
    x='Flow Duration',
    y='Flow Bytes/s',
    title='Attack Density in Feature Space'
)

fig.show()

fig = px.scatter(
    sample,
    x='Flow Packets/s',
    y='Flow Bytes/s',
    color=sample['Label'].apply(lambda x: "Attack" if x != "BENIGN" else "Benign"),
    title='Feature Separability View'
)

fig.show()

entropy = full_df['Label'].value_counts(normalize=True)
fig = px.bar(
    x=entropy.index,
    y=entropy.values,
    title='Attack Label Probability Distribution (Entropy View)'
)

fig.show()

flow_seq = full_df['Flow Bytes/s'].fillna(0).rolling(500).mean()
fig = px.line(
    x=flow_seq.index,
    y=flow_seq.values,
    title='Traffic Intensity Over Sequence'
)

fig.show()

fig = px.histogram(
    full_df,
    x='Label',
    color='source',
    barmode='group',
    title='Category Distribution Stability Across Days'
)

fig.show()

burst = full_df['Label'].apply(lambda x: 1 if x != 'BENIGN' else 0).rolling(1000).sum()

fig = px.line(
    x=burst.index,
    y=burst.values,
    title='Attack Burst Detection (Rolling Window)'
)

fig.show()

corr = sample.select_dtypes(include=np.number).corr()
fig = px.imshow(
    corr,
    title='Feature Correlation Heatmap'
)

fig.show()

fig = px.box(
    sample,
    y='Flow Bytes/s',
    x='Binary',
    title='Outlier Distribution: Attack vs Benign'
)

fig.show()

fig = px.scatter_3d(
    sample,
    x='Flow Duration',
    y='Flow Bytes/s',
    z='Flow Packets/s',
    color='Binary',
    title='3D Traffic Behavior Space'
)

fig.show()

full_df = full_df.replace([np.inf, -np.inf], np.nan)
full_df = full_df.drop_duplicates()
full_df = full_df.dropna()

full_df['Label'] = full_df['Label'].astype(str).str.strip()

le = LabelEncoder()
y = le.fit_transform(full_df['Label'])

label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(label_mapping)

X = full_df.drop(['Label', 'source'], axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""behavioral intelligence features"""

import numpy as np
from sklearn.preprocessing import FunctionTransformer

def feature_engineering(X):
    X = X.copy()
    X['bytes_per_packet'] = (X['Total Length of Fwd Packets'] + X['Total Length of Bwd Packets']) / (X['Total Fwd Packets'] + 1)
    X['packet_burst'] = X['Flow Packets/s'] * X['Flow Bytes/s']
    X['flow_asymmetry'] = X['Total Fwd Packets'] / (X['Total Backward Packets'] + 1)
    X['iat_instability'] = X['Flow IAT Std'] / (X['Flow IAT Mean'] + 1)
    return X
feature_transformer = FunctionTransformer(feature_engineering)

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)
pipeline = Pipeline(steps=[
    ('feature_engineering', feature_transformer),
    ('preprocessing', numeric_pipeline),
    ('model', model)
])

print(X.shape)
print(y.shape)
print(X.isna().sum().sum())

"""MasterDataSetTraining"""

pipeline.fit(X_train, y_train)

from sklearn.metrics import classification_report, accuracy_score
y_pred = pipeline.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""% Reduction for Model Training."""

X_dev = X.sample(frac=0.2, random_state=42)
y_series = pd.Series(y, index=X.index)
y_dev = y_series[X_dev.index]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_dev,
    y_dev,
    test_size=0.2,
    random_state=42,
    stratify=y_dev
)

import numpy as np
from sklearn.preprocessing import FunctionTransformer
def feature_engineering(X):
    X = X.copy()
    X['bytes_per_packet'] = (X['Total Length of Fwd Packets'] + X['Total Length of Bwd Packets']) / (X['Total Fwd Packets'] + 1)
    X['packet_burst'] = X['Flow Packets/s'] * X['Flow Bytes/s']
    X['flow_asymmetry'] = X['Total Fwd Packets'] / (X['Total Backward Packets'] + 1)
    X['iat_instability'] = X['Flow IAT Std'] / (X['Flow IAT Mean'] + 1)
    return X
feature_transformer = FunctionTransformer(feature_engineering)

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight='balanced'
)

print(X.shape)
print(y.shape)
print(X.isna().sum().sum())

pipeline = Pipeline(steps=[
    ('feature_engineering', feature_transformer),
    ('preprocessing', numeric_pipeline),
    ('model', model)
])
pipeline.fit(X_train, y_train)

from sklearn.metrics import classification_report, accuracy_score
y_pred = pipeline.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))