# -*- coding: utf-8 -*-
"""Intrusion detectionANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TFtRs541IuEdIwnrgmFH5OTMr_cdZ4W
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
import plotly.express as px
import plotly.graph_objects as go
# %matplotlib inline
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 150)
sns.set_style('darkgrid')
plt.rcParams['font.size'] = 14
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['patch.edgecolor'] = '#313338'
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.neural_network import MLPClassifier

from google.colab import drive
drive.mount('/content/drive', force_remount=True)
monday=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Monday-WorkingHours.pcap_ISCX.csv")
tuesday=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Tuesday-WorkingHours.pcap_ISCX.csv")
wednesday=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Wednesday-workingHours.pcap_ISCX.csv")
thursday_web=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv")
thursday_infilteration=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")
friday_morning=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Friday-WorkingHours-Morning.pcap_ISCX.csv")
friday_portscan=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv")
friday_DDos=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

monday["source"] = "Monday"
tuesday["source"] = "Tuesday"
wednesday["source"] = "Wednesday"
thursday_web["source"] = "Thursday-Web"
thursday_infilteration["source"] = "Thursday-Infiltration"
friday_morning["source"] = "Friday-Morning"
friday_portscan["source"] = "Friday-PortScan"
friday_DDos["source"] = "Friday-DDoS"

dfs = [monday, tuesday, wednesday, thursday_web,
       thursday_infilteration, friday_morning,
       friday_portscan, friday_DDos]
for df in dfs:
    df.columns = df.columns.str.strip()

for name, df in zip(
    ["Monday", "Tuesday", "Wednesday", "Thursday-Web",
     "Thursday-Infiltration", "Friday-Morning",
     "Friday-PortScan", "Friday-DDoS"],
    dfs
):
    print("\n", name)
    print(df["Label"].value_counts())

full_df = pd.concat(dfs, ignore_index=True)
full_df = full_df.replace([np.inf, -np.inf], np.nan).dropna()
full_df=full_df.drop_duplicates()
full_df=full_df.dropna()

full_df['Label']=full_df['Label'].astype(str).str.strip()

le=LabelEncoder()
y=le.fit_transform(full_df['Label'])
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(label_mapping)

X=full_df.drop(['Label','source'],axis=1)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

def feature_engineering(X):
  X=X.copy()
  X['bytes_per_packet'] = (X['Total Length of Fwd Packets'] + X['Total Length of Bwd Packets']) / (X['Total Fwd Packets'] + 1)
  X['packet_burst'] = X['Flow Packets/s'] * X['Flow Bytes/s']
  X['flow_asymmetry'] = X['Total Fwd Packets'] / (X['Total Backward Packets'] + 1)
  X['iat_instability'] = X['Flow IAT Std'] / (X['Flow IAT Mean'] + 1)
  return X
feature_transformer=FunctionTransformer(feature_engineering)

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
numeric_pipeline=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())
])

from sklearn import pipeline
model=MLPClassifier(hidden_layer_sizes=[50,100,50],max_iter=1000,activation="tanh",early_stopping=True)
pipeline=Pipeline(steps=[
    ('feature_engineering',feature_transformer),
    ('numeric_pipeline',numeric_pipeline),
    ('model',model)
])

print(X.shape())
print(y.shape())
print(X.isna().sum().sum())

pipeline.fit(X_train,y_train)

from sklearn.metrics import accuracy_score
y_pred=pipeline.predict(X_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

"""Reducing the Volume of Data for training"""

X_dev=X.sample(frac=0.2,random_state=42)
y_series=pd.Series(y, index=X.index)
y_dev=y_series[X_dev.index]

X_train, X_test,y_train,y_test=train_test_split(X_dev,y_dev,test_size=0.2,random_state=42, stratify=y_dev)

def feature_engineering(X):
    X = X.copy()
    X['bytes_per_packet'] = (X['Total Length of Fwd Packets'] + X['Total Length of Bwd Packets']) / (X['Total Fwd Packets'] + 1)
    X['packet_burst'] = X['Flow Packets/s'] * X['Flow Bytes/s']
    X['flow_asymmetry'] = X['Total Fwd Packets'] / (X['Total Backward Packets'] + 1)
    X['iat_instability'] = X['Flow IAT Std'] / (X['Flow IAT Mean'] + 1)
    return X
feature_transformer = FunctionTransformer(feature_engineering)

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

from sklearn import pipeline
model=MLPClassifier(hidden_layer_sizes=[50,100,50],max_iter=1000,activation="tanh",early_stopping=True)
pipeline=Pipeline(steps=[
    ('feature_engineering',feature_transformer),
    ('numeric_pipeline',numeric_pipeline),
    ('model',model)
])

pipeline.fit(X_train, y_train)

from sklearn.metrics import classification_report, accuracy_score
y_pred = pipeline.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))